version: '3.8'

services:
  blazorwebuitest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zk147olu
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DatabaseSettings:ConnectionString=mongodb://blazorwebdb:27020
    ports:
      - "5040:80"
      - "5042:443"
    volumes:
      - ./https/:/https:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - blazorwebdb_volume:/data/db