version: '3.8'

services:
  blazorwebuitestx:
    container_name: blazorwebuitestx_ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=19065
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zk147olu
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - MongoDBSettings:ConnectionString=mongodb://blazorwebdb
    ports:
      - 19065:443
      - 5123:80
    depends_on:
      - blazorwebdb
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27022:27017"
    volumes:
      - blazorwebdb_volume:/data/db