version: '3.8'

services:
  blazorwebui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DatabaseSettings:ConnectionString=mongodb://blazorwebdb:27019
    ports:
      - "5040:80"
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - blazorwebdb_volume:/data/db