version: '3.8'

services:
  blazorwebui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=19051
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zk147olu
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5040:80"
      - "5042:443"
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - blazorwebdb_volume:/data/db