version: "3.8"
services:
  blazorwebuitestx:
    image: blazorwebuitestx_ui_image
    build:
      context: .
      dockerfile: BlazorWebUI/Dockerfile
  blazorwebdb:
    image: mongo
volumes:
  blazorwebdb_volume: