version: '3.8'

services:
  blazorwebuitest:
    container_name: blazorwebuitest_ui
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=TestL.31235
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp1.pfx
      - DatabaseSettings:ConnectionString=mongodb://blazorwebdb:27020
    ports:
      - "5040:80"
      - "5042:443"
    depends_on:
      - blazorwebdb
    volumes:
      - ./https/aspnetapp1.pfx:/https/aspnetapp1.pfx:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - blazorwebdb_volume:/data/db