version: '3.8'

services:
  blazorwebuitest:
    container_name: blazorwebuitest_ui
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DatabaseSettings:ConnectionString=mongodb://blazorwebdb:27020
      - PASSWORD_ENV_SEEDED=TestL.31235
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PASSWORD_ENV_SEEDED}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp123.pfx
    args:
      - PASSWORD_ENV_SEEDED=TestL.31235
    restart: unless-stopped
    ports:
      - 15005:443
    depends_on:
      - blazorwebdb
    volumes:
      - ./https/aspnetapp1.pfx:/https/aspnetapp123.pfx:ro
  blazorwebdb:
    container_name: blazorwebdb
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - blazorwebdb_volume:/data/db